INSERT INTO products (user_id, title, description, thumbnail_photo_url, price) VALUES (1, 'mouse', 'wireless mouse', 'URL', 29.45);
INSERT INTO products (user_id, title, description, thumbnail_photo_url, price) VALUES (2, 'keyboards', 'wireless keyboard', 'URL', 199.99);
INSERT INTO products (user_id, title, description, thumbnail_photo_url, price) VALUES (3, 'monitors', 'touch monitor', 'URL', 399.99);
INSERT INTO products (user_id, title, description, thumbnail_photo_url, price) VALUES (4, 'mouse', 'apple wireless mouse', 'URL', 69.55);
INSERT INTO products (user_id, title, description, thumbnail_photo_url, price) VALUES (5, 'keyboards', 'apple wireless keypad', 'URL', 38.45);
INSERT INTO products (user_id, title, description, thumbnail_photo_url, price) VALUES (6, 'hard disks', 'apple USB drive', 'URL', 64.78);
INSERT INTO products (user_id, title, description, thumbnail_photo_url, price) VALUES (7, 'headphones', 'wireless headphone', 'URL', 75.50);
INSERT INTO products (user_id, title, description, thumbnail_photo_url, price) VALUES (8, 'tablets', 'Samsung tablet', 'URL', 999.99);
INSERT INTO products (user_id, title, description, thumbnail_photo_url, price) VALUES (9, 'hard disks', 'Samsung portable hard disk', 'URL', 319.49);
INSERT INTO products (user_id, title, description, thumbnail_photo_url, price) VALUES (10, 'monitors', 'Samsung curved monitor', 'URL', 419.20);
INSERT INTO products (user_id, title, description, thumbnail_photo_url, price) VALUES (11, 'memory cards', 'Lenovo 1TB SSD', 'URL', 249.50);
INSERT INTO products (user_id, title, description, thumbnail_photo_url, price) VALUES (12, 'headphones', 'MS wireless headphone', 'URL', 250.00);
