-- INSERT INTO favourites (product_id, user_id) VALUES (1, 2);
-- INSERT INTO favourites (product_id, user_id) VALUES (3, 4);
-- INSERT INTO favourites (product_id, user_id) VALUES (5, 6);
-- INSERT INTO favourites (product_id, user_id) VALUES (7, 8);
-- INSERT INTO favourites (product_id, user_id) VALUES (9, 10);
-- INSERT INTO favourites (product_id, user_id) VALUES (11, 12);
